// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-keychain.
//
// go-keychain is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

package backend

import (
	"crypto"
	"time"

	"github.com/jeremyhahn/go-keychain/pkg/types"
)

// WrappingAlgorithm identifies the algorithm used to wrap key material for secure transport.
type WrappingAlgorithm string

const (
	// RSA-based wrapping algorithms (PKCS#1 OAEP)
	WrappingAlgorithmRSAES_OAEP_SHA_1   WrappingAlgorithm = "RSAES_OAEP_SHA_1"
	WrappingAlgorithmRSAES_OAEP_SHA_256 WrappingAlgorithm = "RSAES_OAEP_SHA_256"

	// Hybrid wrapping algorithms (RSA + AES-KWP)
	// These use RSA to wrap a temporary AES key, then use that AES key to wrap the target key.
	// Required for wrapping RSA private keys which may exceed RSA key size limits.
	WrappingAlgorithmRSA_AES_KEY_WRAP_SHA_1   WrappingAlgorithm = "RSA_AES_KEY_WRAP_SHA_1"
	WrappingAlgorithmRSA_AES_KEY_WRAP_SHA_256 WrappingAlgorithm = "RSA_AES_KEY_WRAP_SHA_256"

	// GCP-specific hybrid algorithms
	WrappingAlgorithmRSA_OAEP_3072_SHA256_AES_256 WrappingAlgorithm = "RSA_OAEP_3072_SHA256_AES_256"
	WrappingAlgorithmRSA_OAEP_4096_SHA256_AES_256 WrappingAlgorithm = "RSA_OAEP_4096_SHA256_AES_256"
	WrappingAlgorithmRSA_OAEP_4096_SHA256         WrappingAlgorithm = "RSA_OAEP_4096_SHA256"
)

// ImportParameters contains the parameters needed to import a key into a backend.
// These parameters are typically obtained from GetImportParameters and may have
// a limited validity period (e.g., 24 hours for AWS KMS).
type ImportParameters struct {
	// WrappingPublicKey is the public key used to wrap key material for secure transport.
	// The corresponding private key is held securely by the backend (e.g., in an HSM).
	WrappingPublicKey crypto.PublicKey

	// ImportToken is backend-specific metadata required for the import operation.
	// For AWS KMS, this contains metadata that ensures key material is imported correctly.
	// May be nil for backends that don't require it.
	ImportToken []byte

	// Algorithm is the required wrapping algorithm for this import.
	// The algorithm must be supported by the WrappingPublicKey.
	Algorithm WrappingAlgorithm

	// ExpiresAt indicates when these import parameters expire.
	// After expiration, new parameters must be obtained via GetImportParameters.
	// May be nil for backends that don't expire import parameters.
	ExpiresAt *time.Time

	// KeySpec describes the type of key that can be imported with these parameters.
	// For example, "RSA_2048", "AES_256", etc.
	KeySpec string
}

// WrappedKeyMaterial represents key material that has been wrapped for secure transport.
// The wrapped material can be safely transmitted over untrusted channels and imported
// into a backend that holds the corresponding unwrapping key.
type WrappedKeyMaterial struct {
	// WrappedKey is the encrypted key material.
	// For hybrid algorithms, this contains both the wrapped AES key and the
	// AES-encrypted target key concatenated together.
	WrappedKey []byte

	// Algorithm is the wrapping algorithm that was used.
	// This must match the algorithm specified in ImportParameters.
	Algorithm WrappingAlgorithm

	// ImportToken is the token from the corresponding ImportParameters.
	// Required by some backends (e.g., AWS KMS) to associate the wrapped
	// key with the correct import operation.
	ImportToken []byte

	// Metadata contains additional backend-specific information about the wrapped key.
	// This may include key type, size, usage flags, etc.
	Metadata map[string]string
}

// ImportExportBackend extends Backend with key import/export capabilities.
// This interface enables secure key transport between systems, such as:
//   - Importing externally generated keys into an HSM/KMS
//   - Exporting keys from one HSM/KMS to another (if supported)
//   - Migrating keys between cloud providers
//
// Not all backends support all operations:
//   - AWS KMS supports import but not export
//   - Cloud HSMs typically support both import and export
//   - Software backends may support both for testing/development
type ImportExportBackend interface {
	types.Backend

	// GetImportParameters retrieves the parameters needed to import a key.
	// This typically includes a wrapping public key generated by the backend's HSM,
	// and may include an import token for associating the import with these parameters.
	//
	// The returned parameters may have a limited validity period (e.g., 24 hours for AWS).
	// After expiration, new parameters must be obtained.
	//
	// The algorithm parameter specifies the wrapping algorithm to use. Different algorithms
	// may be required for different key types (e.g., hybrid algorithms for RSA private keys).
	//
	// Returns an error if the backend doesn't support import or the algorithm is not supported.
	GetImportParameters(attrs *types.KeyAttributes, algorithm WrappingAlgorithm) (*ImportParameters, error)

	// WrapKey wraps key material for secure transport using the specified parameters.
	// This operation is typically performed locally (outside the backend) before
	// importing the key material.
	//
	// For RSA-based algorithms, the key material is encrypted directly with the
	// wrapping public key.
	//
	// For hybrid algorithms (RSA + AES-KWP):
	//   1. Generate a random AES-256 key
	//   2. Encrypt the AES key with the RSA public key using OAEP
	//   3. Encrypt the target key material with the AES key using AES-KWP
	//   4. Concatenate the wrapped AES key and wrapped target key
	//
	// Returns WrappedKeyMaterial that can be passed to ImportKey.
	WrapKey(keyMaterial []byte, params *ImportParameters) (*WrappedKeyMaterial, error)

	// UnwrapKey unwraps key material that was previously wrapped with WrapKey.
	// This operation is typically performed by the backend's HSM using the
	// private key corresponding to the wrapping public key.
	//
	// For testing and software backends, this operation may be performed locally.
	// For hardware backends (HSM/KMS), the unwrapping happens securely within
	// the hardware and the plaintext key material never leaves the secure boundary.
	//
	// Returns the unwrapped (plaintext) key material.
	// Returns an error if unwrapping fails (e.g., due to incorrect parameters or corruption).
	UnwrapKey(wrapped *WrappedKeyMaterial, params *ImportParameters) ([]byte, error)

	// ImportKey imports externally generated key material into the backend.
	// The key material must be wrapped using parameters obtained from GetImportParameters.
	//
	// The import process:
	//   1. Validates the import token (if required)
	//   2. Unwraps the key material using the backend's private unwrapping key (in HSM)
	//   3. Stores the key material securely in the backend
	//   4. Associates the key with the provided attributes
	//
	// After successful import, the key can be used like any other key in the backend
	// (e.g., for signing, decryption, etc.).
	//
	// Security note: The unwrapping private key never leaves the HSM, ensuring that
	// even though the key material traverses an untrusted channel, it remains protected.
	//
	// Returns an error if:
	//   - The import token is invalid or expired
	//   - Unwrapping fails (wrong algorithm, corrupted data, etc.)
	//   - A key with the same attributes already exists
	//   - The backend doesn't support import
	ImportKey(attrs *types.KeyAttributes, wrapped *WrappedKeyMaterial) error

	// ExportKey exports a key in wrapped form for secure transport.
	// This allows migrating keys from one backend to another while maintaining security.
	//
	// The export process wraps the key material using the specified algorithm.
	// The recipient must have the corresponding unwrapping key to recover the key material.
	//
	// Important security considerations:
	//   - Not all backends support key export (e.g., AWS KMS)
	//   - Some backends may restrict export to backup/recovery scenarios
	//   - Hardware-backed keys may have policies that prevent export
	//   - Export should only be used when absolutely necessary
	//
	// Returns WrappedKeyMaterial that can be unwrapped by the recipient.
	// Returns ErrNotSupported if the backend doesn't support key export.
	// Returns ErrOperationNotPermitted if the key's policy prevents export.
	ExportKey(attrs *types.KeyAttributes, algorithm WrappingAlgorithm) (*WrappedKeyMaterial, error)
}
