linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - typecheck

linters-settings:
  gofmt:
    simplify: false
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - composites
      - nilness
      - unreachable

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude deprecated API warnings - we intentionally use some deprecated APIs
  exclude-use-default: false

  # Exclude directories
  exclude-dirs:
    - vendor

  # Exclude files
  exclude-files:
    - ".*\\.pb\\.go$"

  exclude-rules:
    # Exclude deprecation warnings
    - linters:
        - staticcheck
      text: "SA1019"
    # Exclude protobuf generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    # Exclude vendor directory
    - path: "vendor/"
      linters:
        - all

run:
  timeout: 10m
  tests: true
