// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-xkms.
//
// go-xkms is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

package staticpw

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/jeremyhahn/go-xkms/pkg/types"
)

// encryptedPrefix marks an encrypted password field.
const encryptedPrefix = "ENC:"

// EncryptedStore wraps a Store and transparently encrypts the Password field
// on write using a types.SymmetricEncrypter. Reads return encrypted passwords
// by default; use GetDecrypted for on-demand decryption.
type EncryptedStore struct {
	inner     Store
	encrypter types.SymmetricEncrypter
}

// NewEncryptedStore creates an EncryptedStore that wraps inner and uses the
// provided SymmetricEncrypter for password encryption and decryption.
func NewEncryptedStore(inner Store, encrypter types.SymmetricEncrypter) (*EncryptedStore, error) {
	if inner == nil {
		return nil, ErrNilStore
	}
	if encrypter == nil {
		return nil, ErrNilEncrypter
	}
	return &EncryptedStore{
		inner:     inner,
		encrypter: encrypter,
	}, nil
}

// Add encrypts the password field and delegates to the inner store.
func (s *EncryptedStore) Add(pw *StaticPassword) error {
	encrypted, err := s.encryptPassword(pw.Password)
	if err != nil {
		return err
	}

	// Create a copy to avoid mutating the caller's struct.
	encPW := *pw
	encPW.Password = encrypted

	if err := s.inner.Add(&encPW); err != nil {
		return err
	}

	// Propagate the ID generated by the inner store back to the caller.
	pw.ID = encPW.ID
	pw.CreatedAt = encPW.CreatedAt
	pw.UpdatedAt = encPW.UpdatedAt
	return nil
}

// Get retrieves a password entry with the password field still encrypted.
// Use GetDecrypted to retrieve with on-demand decryption.
func (s *EncryptedStore) Get(idOrName string) (*StaticPassword, error) {
	return s.inner.Get(idOrName)
}

// GetDecrypted retrieves a password entry and decrypts the password field
// on demand.
func (s *EncryptedStore) GetDecrypted(idOrName string) (*StaticPassword, error) {
	pw, err := s.inner.Get(idOrName)
	if err != nil {
		return nil, err
	}

	decrypted, err := s.decryptPassword(pw.Password)
	if err != nil {
		return nil, err
	}

	// Return a copy with decrypted password.
	result := *pw
	result.Password = decrypted
	return &result, nil
}

// List returns all entries with passwords still encrypted.
func (s *EncryptedStore) List() ([]*StaticPassword, error) {
	return s.inner.List()
}

// Update encrypts the password field and delegates to the inner store.
func (s *EncryptedStore) Update(pw *StaticPassword) error {
	encrypted, err := s.encryptPassword(pw.Password)
	if err != nil {
		return err
	}

	encPW := *pw
	encPW.Password = encrypted
	return s.inner.Update(&encPW)
}

// Delete delegates to the inner store.
func (s *EncryptedStore) Delete(idOrName string) error {
	return s.inner.Delete(idOrName)
}

// ForceDelete removes an entry bypassing the read-only check.
func (s *EncryptedStore) ForceDelete(idOrName string) error {
	return s.inner.ForceDelete(idOrName)
}

// ListByFolder returns all entries in the given folder and subfolders with
// passwords still encrypted.
func (s *EncryptedStore) ListByFolder(folderPath string) ([]*StaticPassword, error) {
	return s.inner.ListByFolder(folderPath)
}

// ListByFolderDirect returns entries directly in the specified folder,
// excluding subfolders, with passwords still encrypted.
func (s *EncryptedStore) ListByFolderDirect(folderPath string) ([]*StaticPassword, error) {
	return s.inner.ListByFolderDirect(folderPath)
}

// ListFolders delegates to the inner store.
func (s *EncryptedStore) ListFolders() ([]string, error) {
	return s.inner.ListFolders()
}

// CreateFolder delegates to the inner store.
func (s *EncryptedStore) CreateFolder(path string) error {
	return s.inner.CreateFolder(path)
}

// RemoveFolder delegates to the inner store.
func (s *EncryptedStore) RemoveFolder(path string) error {
	return s.inner.RemoveFolder(path)
}

// MoveToFolder decrypts the entry, deletes the old key, updates the folder,
// and re-adds the entry with encryption.
func (s *EncryptedStore) MoveToFolder(idOrName string, folderPath string) error {
	// Get the decrypted entry so we can re-encrypt at the new location.
	pw, err := s.GetDecrypted(idOrName)
	if err != nil {
		return err
	}

	if pw.FolderPath == folderPath {
		return ErrMoveToSameFolder
	}

	// Delete the old entry.
	if delErr := s.inner.Delete(pw.ID); delErr != nil {
		return delErr
	}

	// Update folder path and re-add (Add will regenerate ID and encrypt).
	pw.FolderPath = folderPath
	pw.ID = generateID(pw.Name, pw.FolderPath)
	pw.UpdatedAt = time.Now()

	return s.Add(pw)
}

// Close delegates to the inner store.
func (s *EncryptedStore) Close() error {
	return s.inner.Close()
}

// MigrateToEncrypted reads all existing plaintext entries and re-writes
// them with encrypted password fields. Already-encrypted entries are skipped.
func (s *EncryptedStore) MigrateToEncrypted() error {
	passwords, err := s.inner.List()
	if err != nil {
		return err
	}

	for _, pw := range passwords {
		// Skip already-encrypted entries.
		if strings.HasPrefix(pw.Password, encryptedPrefix) {
			continue
		}

		encrypted, encErr := s.encryptPassword(pw.Password)
		if encErr != nil {
			return encErr
		}
		pw.Password = encrypted
		if updErr := s.inner.Update(pw); updErr != nil {
			return updErr
		}
	}

	return nil
}

// encryptPassword encrypts a plaintext password using the SymmetricEncrypter.
// The result is "ENC:" + base64(json(EncryptedData)).
func (s *EncryptedStore) encryptPassword(plaintext string) (string, error) {
	// Don't double-encrypt.
	if strings.HasPrefix(plaintext, encryptedPrefix) {
		return plaintext, nil
	}

	encData, err := s.encrypter.Encrypt([]byte(plaintext), nil)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrEncryptFailed, err)
	}

	jsonBytes, err := json.Marshal(encData)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrMarshalFailed, err)
	}

	return encryptedPrefix + base64.StdEncoding.EncodeToString(jsonBytes), nil
}

// decryptPassword decrypts an "ENC:<base64>" password using the SymmetricEncrypter.
// If the password is not encrypted (no prefix), it is returned as-is for
// backward compatibility.
func (s *EncryptedStore) decryptPassword(stored string) (string, error) {
	if !strings.HasPrefix(stored, encryptedPrefix) {
		return stored, nil
	}

	encoded := strings.TrimPrefix(stored, encryptedPrefix)
	jsonBytes, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrDecryptFailed, err)
	}

	var encData types.EncryptedData
	if err := json.Unmarshal(jsonBytes, &encData); err != nil {
		return "", fmt.Errorf("%w: %v", ErrDecryptFailed, err)
	}

	plaintext, err := s.encrypter.Decrypt(&encData, nil)
	if err != nil {
		return "", fmt.Errorf("%w: %v", ErrDecryptFailed, err)
	}

	return string(plaintext), nil
}

// Verify interface compliance at compile time.
var _ Store = (*EncryptedStore)(nil)
