// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-xkms.
//
// go-xkms is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

package services

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/jeremyhahn/go-xkms/pkg/pivcert"
	"github.com/jeremyhahn/go-xkms/pkg/pkcs11/manager"
	"github.com/jeremyhahn/go-xkms/xkey/pkg/backendregistry"
	"github.com/jeremyhahn/go-xkms/xkey/pkg/config"
)

// PKCS11 service errors.
var (
	ErrPKCS11ServiceNotInitialized = errors.New("pkcs11_service: manager not initialized")
	ErrPKCS11ModuleRequired        = errors.New("pkcs11_service: module path is required")
	ErrPKCS11LabelRequired         = errors.New("pkcs11_service: token label is required")
	ErrPKCS11SOPINRequired         = errors.New("pkcs11_service: security officer PIN is required")
	ErrPKCS11UserPINRequired       = errors.New("pkcs11_service: user PIN is required")
	ErrPKCS11NoSlotsAvailable      = errors.New("pkcs11_service: no slots available in module")
	ErrPKCS11SlotNotFound          = errors.New("pkcs11_service: specified slot not found")
	ErrPKCS11ConfigPersistFailed   = errors.New("pkcs11_service: failed to persist config")
)

// softhsm2ConfigTemplate is the default SoftHSM2 configuration.
const softhsm2ConfigTemplate = `# SoftHSM2 configuration - auto-generated by xkey
directories.tokendir = %s
objectstore.backend = file
log.level = INFO
slots.removable = false
`

// PKCS11ModuleInfo describes an available PKCS#11 module for the frontend.
type PKCS11ModuleInfo struct {
	ID          string           `json:"id"`
	DisplayName string           `json:"display_name"`
	LibraryPath string           `json:"library_path"`
	State       string           `json:"state"`
	Slots       []PKCS11SlotInfo `json:"slots"`
	ErrorMsg    string           `json:"error_msg,omitempty"`
}

// PKCS11SlotInfo describes a PKCS#11 slot for the frontend.
type PKCS11SlotInfo struct {
	SlotID          uint   `json:"slot_id"`
	Label           string `json:"label"`
	Serial          string `json:"serial"`
	Manufacturer    string `json:"manufacturer"`
	Model           string `json:"model"`
	TokenPresent    bool   `json:"token_present"`
	Initialized     bool   `json:"initialized"`
	HardwareVersion string `json:"hardware_version"`
	FirmwareVersion string `json:"firmware_version"`
}

// PKCS11TokenInfo describes a PKCS#11 token for the frontend.
type PKCS11TokenInfo struct {
	ModuleID     string `json:"module_id"`
	ModuleName   string `json:"module_name"`
	SlotID       uint   `json:"slot_id"`
	Label        string `json:"label"`
	Manufacturer string `json:"manufacturer"`
	Model        string `json:"model"`
	Serial       string `json:"serial"`
	Initialized  bool   `json:"initialized"`
	Connected    bool   `json:"connected"`
}

// PKCS11ConnectionInfo describes an active PKCS#11 connection for the frontend.
type PKCS11ConnectionInfo struct {
	ModuleID   string `json:"module_id"`
	SlotID     uint   `json:"slot_id"`
	TokenLabel string `json:"token_label"`
}

// ProbeResult describes a detected PKCS#11 module for the frontend.
type ProbeResult struct {
	LibraryPath string `json:"library_path"`
	DisplayName string `json:"display_name"`
}

// PKCS11Service exposes PKCS#11 token management operations to the frontend.
// It wraps pkg/pkcs11/manager.Manager and is bound to the Wails runtime so
// every exported method is callable from the Svelte frontend.
// PKCS11ConnectHook is called after a PKCS11 token is successfully connected.
// It receives the module ID, library path, slot ID, user PIN, SO PIN (management key),
// and token label.
type PKCS11ConnectHook func(moduleID, libraryPath string, slotID uint, userPIN, soPin, tokenLabel string)

// PKCS11DisconnectHook is called after a PKCS#11 token is disconnected.
// It receives the module ID and slot ID so callers can clean up resources.
type PKCS11DisconnectHook func(moduleID string, slotID uint)

type PKCS11Service struct {
	ctx            context.Context
	log            *slog.Logger
	manager        manager.Manager
	registry       backendregistry.Registry
	connectHook    PKCS11ConnectHook
	disconnectHook PKCS11DisconnectHook

	// testedModules tracks modules that passed TestConnection and are still
	// registered, so a subsequent RegisterModule call can reuse them instead
	// of paying the C_Initialize cost again (YubiKey libykcs11 takes several
	// seconds to enumerate USB on each load).
	testedModules   map[string]string // libraryPath -> moduleID
	testedModulesMu sync.RWMutex
}

// NewPKCS11Service creates a new PKCS11Service with a fresh manager.
func NewPKCS11Service() *PKCS11Service {
	m := manager.New()
	slog.Info("pkcs11_service: created", "manager_available", m.IsAvailable())
	return &PKCS11Service{
		log:           slog.Default().With("component", "pkcs11_service"),
		manager:       m,
		testedModules: make(map[string]string),
	}
}

// SetContext is called by the Wails startup lifecycle hook.
func (s *PKCS11Service) SetContext(ctx context.Context) {
	s.ctx = ctx
}

// SetConnectHook registers a callback that fires after a PKCS#11 token
// is successfully connected. This allows registering the connected token
// as an xkms backend for PIV key generation and other operations.
func (s *PKCS11Service) SetConnectHook(fn PKCS11ConnectHook) {
	s.connectHook = fn
}

// SetDisconnectHook registers a callback that fires after a PKCS#11 token
// is disconnected. This allows unregistering resources (e.g., FIDO2 key backends).
func (s *PKCS11Service) SetDisconnectHook(fn PKCS11DisconnectHook) {
	s.disconnectHook = fn
}

// SetManager sets the underlying PKCS#11 manager.
// This allows injecting a manager with custom configuration or for testing.
func (s *PKCS11Service) SetManager(m manager.Manager) {
	s.manager = m
}

// GetManager returns the underlying PKCS#11 manager.
func (s *PKCS11Service) GetManager() manager.Manager {
	return s.manager
}

// SetRegistry sets the backend registry for state synchronization.
// When set, Connect/Disconnect update the registry state so the frontend
// reflects the actual PKCS#11 session status.
func (s *PKCS11Service) SetRegistry(r backendregistry.Registry) {
	s.registry = r
}

// IsAvailable returns true if PKCS#11 support is compiled in.
func (s *PKCS11Service) IsAvailable() bool {
	if s.manager == nil {
		return false
	}
	return s.manager.IsAvailable()
}

// Close shuts down the PKCS#11 manager and releases all resources.
func (s *PKCS11Service) Close() error {
	if s.manager == nil {
		return nil
	}
	return s.manager.Close()
}

// ProbeModules detects available PKCS#11 modules on the system.
// Returns a list of library paths and suggested display names.
func (s *PKCS11Service) ProbeModules() []ProbeResult {
	probed := manager.ProbeModulesWithNames()
	results := make([]ProbeResult, len(probed))
	for i, p := range probed {
		results[i] = ProbeResult{
			LibraryPath: p.LibraryPath,
			DisplayName: p.DisplayName,
		}
	}
	return results
}

// isSoftHSM2Module checks if the library path is a SoftHSM2 module.
func isSoftHSM2Module(libraryPath string) bool {
	base := strings.ToLower(filepath.Base(libraryPath))
	return strings.Contains(base, "softhsm")
}

// ensureSoftHSM2Config ensures the SoftHSM2 configuration exists.
// If the SOFTHSM2_CONF environment variable is not set and no config exists,
// it creates a default configuration in ~/.config/softhsm2/.
func (s *PKCS11Service) ensureSoftHSM2Config() error {
	// Check if already configured via environment
	if os.Getenv("SOFTHSM2_CONF") != "" {
		s.log.Debug("SoftHSM2 config from environment", "path", os.Getenv("SOFTHSM2_CONF"))
		return nil
	}

	// Check common system paths
	systemPaths := []string{
		"/etc/softhsm2.conf",
		"/etc/softhsm/softhsm2.conf",
	}
	for _, p := range systemPaths {
		if _, err := os.Stat(p); err == nil {
			s.log.Debug("SoftHSM2 system config found", "path", p)
			return nil
		}
	}

	// Create user config directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	configDir := filepath.Join(homeDir, ".config", "softhsm2")
	tokenDir := filepath.Join(configDir, "tokens")
	configPath := filepath.Join(configDir, "softhsm2.conf")

	// Check if user config already exists
	if _, err := os.Stat(configPath); err == nil {
		// Config exists, just set the environment variable
		if err := os.Setenv("SOFTHSM2_CONF", configPath); err != nil {
			return fmt.Errorf("failed to set SOFTHSM2_CONF: %w", err)
		}
		s.log.Info("SoftHSM2 user config found", "path", configPath)
		return nil
	}

	// Create directories
	if err := os.MkdirAll(tokenDir, 0700); err != nil {
		return fmt.Errorf("failed to create SoftHSM2 token directory: %w", err)
	}

	// Write config file
	configContent := fmt.Sprintf(softhsm2ConfigTemplate, tokenDir)
	if err := os.WriteFile(configPath, []byte(configContent), 0600); err != nil {
		return fmt.Errorf("failed to write SoftHSM2 config: %w", err)
	}

	// Set environment variable for current process
	if err := os.Setenv("SOFTHSM2_CONF", configPath); err != nil {
		return fmt.Errorf("failed to set SOFTHSM2_CONF: %w", err)
	}

	s.log.Info("SoftHSM2 config auto-created", "config", configPath, "tokens", tokenDir)
	return nil
}

// RegisterModule registers a PKCS#11 library with the manager.
// Returns the module ID that can be used for subsequent operations.
// For SoftHSM2 modules, automatically creates configuration if needed.
func (s *PKCS11Service) RegisterModule(libraryPath, displayName string) (string, error) {
	if s.manager == nil {
		return "", ErrPKCS11ServiceNotInitialized
	}
	if libraryPath == "" {
		return "", ErrPKCS11ModuleRequired
	}

	// Reuse a pre-tested module registration if TestConnection already loaded
	// this library. This avoids a second C_Initialize which can take several
	// seconds on YubiKey (libykcs11 enumerates USB/CCID on every load).
	if s.testedModules != nil {
		s.testedModulesMu.RLock()
		existingID, ok := s.testedModules[libraryPath]
		s.testedModulesMu.RUnlock()
		if ok {
			if _, err := s.manager.GetModule(existingID); err == nil {
				s.log.Info("PKCS#11 module reused from TestConnection",
					"module_id", existingID, "library", libraryPath)
				if persistErr := s.persistModule(existingID, libraryPath, displayName); persistErr != nil {
					s.log.Error("PKCS#11 module reused but config persistence failed",
						"module_id", existingID, "error", persistErr)
				}
				// Clear the cache entry — it has now been "promoted" to a real registration.
				s.testedModulesMu.Lock()
				delete(s.testedModules, libraryPath)
				s.testedModulesMu.Unlock()
				return existingID, nil
			}
			// Stale cache entry — module no longer registered. Drop it and re-register.
			s.testedModulesMu.Lock()
			delete(s.testedModules, libraryPath)
			s.testedModulesMu.Unlock()
		}
	}

	// Auto-configure SoftHSM2 if needed
	if isSoftHSM2Module(libraryPath) {
		if err := s.ensureSoftHSM2Config(); err != nil {
			s.log.Error("failed to configure SoftHSM2", "error", err)
			return "", fmt.Errorf("SoftHSM2 configuration failed: %w", err)
		}
	}

	moduleID, err := s.manager.RegisterModule(libraryPath, displayName)
	if err != nil {
		s.log.Error("failed to register PKCS#11 module",
			"library", libraryPath,
			"error", err)
		return "", err
	}

	// Log the registered module info
	mod, modErr := s.manager.GetModule(moduleID)
	if modErr == nil {
		s.log.Info("PKCS#11 module registered",
			"module_id", moduleID,
			"library", libraryPath,
			"slots", len(mod.Slots))
	}

	// Persist the PKCS#11 backend to the unified config so it survives restarts.
	if persistErr := s.persistModule(moduleID, libraryPath, displayName); persistErr != nil {
		s.log.Error("PKCS#11 module registered in-memory but config persistence failed",
			"module_id", moduleID, "error", persistErr)
		// Don't fail the registration — the module is usable this session.
	}

	return moduleID, nil
}

// persistModule saves a PKCS#11 module entry to the unified config file.
func (s *PKCS11Service) persistModule(moduleID, libraryPath, displayName string) error {
	ucfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrPKCS11ConfigPersistFailed, err)
	}

	entry := config.LocalBackendConfig{
		ID:       moduleID,
		Category: "pkcs11",
		Name:     displayName,
		PKCS11: &config.PKCS11BackendConfig{
			LibraryPath: libraryPath,
		},
	}

	// Replace existing entry with same ID, or append.
	replaced := false
	for i, existing := range ucfg.Backends.Local {
		if existing.ID == moduleID {
			ucfg.Backends.Local[i] = entry
			replaced = true
			break
		}
	}
	if !replaced {
		ucfg.Backends.Local = append(ucfg.Backends.Local, entry)
	}

	if saveErr := config.Save(ucfg); saveErr != nil {
		return fmt.Errorf("%w: %v", ErrPKCS11ConfigPersistFailed, saveErr)
	}

	s.log.Info("PKCS#11 module persisted to config", "module_id", moduleID)
	return nil
}

// RegisterModuleFromConfig registers a PKCS#11 module from persisted config.
// Unlike RegisterModule, this does NOT re-persist to config (avoiding circular
// writes during startup restoration). The moduleID is used as-is rather than
// being generated by the manager.
func (s *PKCS11Service) RegisterModuleFromConfig(moduleID, libraryPath, displayName string) (string, error) {
	if s.manager == nil {
		return "", ErrPKCS11ServiceNotInitialized
	}
	if libraryPath == "" {
		return "", ErrPKCS11ModuleRequired
	}

	// Auto-configure SoftHSM2 if needed
	if isSoftHSM2Module(libraryPath) {
		if err := s.ensureSoftHSM2Config(); err != nil {
			s.log.Error("failed to configure SoftHSM2", "error", err)
			return "", fmt.Errorf("SoftHSM2 configuration failed: %w", err)
		}
	}

	id, err := s.manager.RegisterModule(libraryPath, displayName)
	if err != nil {
		s.log.Error("failed to restore PKCS#11 module from config",
			"module_id", moduleID, "library", libraryPath, "error", err)
		return "", err
	}

	s.log.Info("PKCS#11 module restored from config",
		"module_id", id, "library", libraryPath)
	return id, nil
}

// UnregisterModule unregisters a PKCS#11 module.
func (s *PKCS11Service) UnregisterModule(moduleID string) error {
	if s.manager == nil {
		return ErrPKCS11ServiceNotInitialized
	}
	return s.manager.UnregisterModule(moduleID)
}

// RefreshSlots refreshes the slot list for a module.
func (s *PKCS11Service) RefreshSlots(moduleID string) ([]PKCS11SlotInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}
	slots, err := s.manager.RefreshSlots(moduleID)
	if err != nil {
		return nil, err
	}
	return convertSlots(slots), nil
}

// GetModule returns information about a registered module.
func (s *PKCS11Service) GetModule(moduleID string) (*PKCS11ModuleInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}
	mod, err := s.manager.GetModule(moduleID)
	if err != nil {
		return nil, err
	}
	return convertModule(mod), nil
}

// ListModules returns all registered PKCS#11 modules.
func (s *PKCS11Service) ListModules() []PKCS11ModuleInfo {
	if s.manager == nil {
		return nil
	}
	modules := s.manager.ListModules()
	result := make([]PKCS11ModuleInfo, len(modules))
	for i := range modules {
		result[i] = *convertModule(&modules[i])
	}
	return result
}

// ListTokens returns all tokens across all registered modules.
func (s *PKCS11Service) ListTokens() []PKCS11TokenInfo {
	if s.manager == nil {
		return nil
	}
	tokens := s.manager.ListTokens()
	result := make([]PKCS11TokenInfo, len(tokens))
	for i, t := range tokens {
		result[i] = PKCS11TokenInfo{
			ModuleID:     t.ModuleID,
			ModuleName:   t.ModuleName,
			SlotID:       t.SlotID,
			Label:        t.Label,
			Manufacturer: t.Manufacturer,
			Model:        t.Model,
			Serial:       t.Serial,
			Initialized:  t.Initialized,
			Connected:    t.Connected,
		}
	}
	return result
}

// InitializeToken initializes a new token with SO PIN and User PIN.
func (s *PKCS11Service) InitializeToken(moduleID string, slotID uint, label, soPin, userPin string) error {
	if s.manager == nil {
		return ErrPKCS11ServiceNotInitialized
	}
	if label == "" {
		return ErrPKCS11LabelRequired
	}
	if soPin == "" {
		return ErrPKCS11SOPINRequired
	}
	if userPin == "" {
		return ErrPKCS11UserPINRequired
	}

	s.log.Info("initializing PKCS#11 token",
		"module_id", moduleID,
		"slot_id", slotID,
		"label", label)

	// Get module info to validate slot
	mod, err := s.manager.GetModule(moduleID)
	if err != nil {
		s.log.Error("failed to get module info", "module_id", moduleID, "error", err)
		return fmt.Errorf("module not found: %w", err)
	}

	if len(mod.Slots) == 0 {
		s.log.Error("no slots available in module", "module_id", moduleID)
		return ErrPKCS11NoSlotsAvailable
	}

	// Check if slot exists
	slotFound := false
	for _, slot := range mod.Slots {
		if slot.SlotID == slotID {
			slotFound = true
			s.log.Debug("found slot", "slot_id", slotID, "token_present", slot.TokenPresent, "initialized", slot.Initialized)
			break
		}
	}
	if !slotFound {
		s.log.Error("slot not found", "module_id", moduleID, "slot_id", slotID, "available_slots", len(mod.Slots))
		return fmt.Errorf("%w: slot %d (module has %d slots)", ErrPKCS11SlotNotFound, slotID, len(mod.Slots))
	}

	if err := s.manager.InitializeToken(moduleID, slotID, label, soPin, userPin); err != nil {
		s.log.Error("failed to initialize token",
			"module_id", moduleID,
			"slot_id", slotID,
			"error", err)
		return fmt.Errorf("token initialization failed: %w", err)
	}

	s.log.Info("PKCS#11 token initialized successfully",
		"module_id", moduleID,
		"slot_id", slotID,
		"label", label)

	return nil
}

// GetModuleSlots returns the slots for a registered module.
// This allows the frontend to show available slots for selection.
func (s *PKCS11Service) GetModuleSlots(moduleID string) ([]PKCS11SlotInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}

	mod, err := s.manager.GetModule(moduleID)
	if err != nil {
		return nil, err
	}

	return convertSlots(mod.Slots), nil
}

// Connect connects to a token and returns the backend.
// The backend can be used for cryptographic operations.
func (s *PKCS11Service) Connect(moduleID string, slotID uint, userPin, soPin string) error {
	if s.manager == nil {
		return ErrPKCS11ServiceNotInitialized
	}
	if userPin == "" {
		return ErrPKCS11UserPINRequired
	}

	s.log.Info("connecting to PKCS#11 token",
		"module_id", moduleID,
		"slot_id", slotID)

	// Get module info to validate slot
	mod, err := s.manager.GetModule(moduleID)
	if err != nil {
		s.log.Error("failed to get module info", "module_id", moduleID, "error", err)
		return fmt.Errorf("module not found: %w", err)
	}

	if len(mod.Slots) == 0 {
		s.log.Error("no slots available in module", "module_id", moduleID)
		return ErrPKCS11NoSlotsAvailable
	}

	// Log available slots for debugging
	s.log.Debug("module slots",
		"module_id", moduleID,
		"slot_count", len(mod.Slots))
	for _, slot := range mod.Slots {
		s.log.Debug("slot info",
			"slot_id", slot.SlotID,
			"label", slot.Label,
			"token_present", slot.TokenPresent,
			"initialized", slot.Initialized)
	}

	// Check if slot exists and is initialized
	slotFound := false
	var tokenLabel string
	for _, slot := range mod.Slots {
		if slot.SlotID == slotID {
			slotFound = true
			tokenLabel = slot.Label
			if !slot.TokenPresent {
				return fmt.Errorf("no token present in slot %d", slotID)
			}
			if !slot.Initialized {
				return fmt.Errorf("token in slot %d is not initialized", slotID)
			}
			break
		}
	}
	if !slotFound {
		// Try to find any available slot
		availableSlots := make([]uint, 0)
		for _, slot := range mod.Slots {
			if slot.TokenPresent && slot.Initialized {
				availableSlots = append(availableSlots, slot.SlotID)
			}
		}
		if len(availableSlots) > 0 {
			return fmt.Errorf("%w: slot %d not found, available initialized slots: %v", ErrPKCS11SlotNotFound, slotID, availableSlots)
		}
		return fmt.Errorf("%w: slot %d (module has %d slots, none initialized)", ErrPKCS11SlotNotFound, slotID, len(mod.Slots))
	}

	_, err = s.manager.Connect(moduleID, slotID, userPin, soPin)
	if err != nil {
		s.log.Error("failed to connect to PKCS#11 token",
			"module_id", moduleID,
			"slot_id", slotID,
			"error", err)
		return fmt.Errorf("connection failed: %w", err)
	}

	s.log.Info("PKCS#11 token connected successfully",
		"module_id", moduleID,
		"slot_id", slotID)

	// Update backend registry state to reflect the live PKCS#11 session.
	// Store connection parameters in metadata so PIV cert storage can be
	// created from registry metadata for on-device certificate storage.
	if s.registry != nil {
		if rb, getErr := s.registry.Get(moduleID); getErr == nil {
			rb.SetState(backendregistry.StateReady)
			if rb.Metadata == nil {
				rb.Metadata = make(map[string]string)
			}
			rb.Metadata["connected_slot"] = fmt.Sprintf("%d", slotID)
			rb.Metadata["library_path"] = mod.LibraryPath
			if tokenLabel != "" {
				rb.Metadata["token_label"] = tokenLabel
			}
		}
	}

	// Notify hook so the PKCS#11 token can be registered as an xkms backend
	// for PIV key generation and other key operations.
	if s.connectHook != nil {
		s.connectHook(moduleID, mod.LibraryPath, slotID, userPin, soPin, tokenLabel)
	}

	return nil
}

// Disconnect closes the PKCS#11 session and logs out from the token.
func (s *PKCS11Service) Disconnect(moduleID string, slotID uint) error {
	if s.manager == nil {
		return ErrPKCS11ServiceNotInitialized
	}
	if err := s.manager.Disconnect(moduleID, slotID); err != nil {
		return err
	}

	s.log.Info("PKCS#11 token disconnected",
		"module_id", moduleID,
		"slot_id", slotID)

	// Update backend registry state to reflect the closed session.
	if s.registry != nil {
		if rb, getErr := s.registry.Get(moduleID); getErr == nil {
			rb.SetState(backendregistry.StateOffline)
		}
	}

	// Notify hook so callers can clean up resources (e.g., FIDO2 key backends).
	if s.disconnectHook != nil {
		s.disconnectHook(moduleID, slotID)
	}

	return nil
}

// GetConnection returns information about an active connection.
func (s *PKCS11Service) GetConnection(moduleID string, slotID uint) (*PKCS11ConnectionInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}
	conn, err := s.manager.GetConnection(moduleID, slotID)
	if err != nil {
		return nil, err
	}
	return &PKCS11ConnectionInfo{
		ModuleID:   conn.ModuleID,
		SlotID:     conn.SlotID,
		TokenLabel: conn.TokenLabel,
	}, nil
}

// ListConnections returns all active connections.
func (s *PKCS11Service) ListConnections() []PKCS11ConnectionInfo {
	if s.manager == nil {
		return nil
	}
	connections := s.manager.ListConnections()
	result := make([]PKCS11ConnectionInfo, len(connections))
	for i, c := range connections {
		result[i] = PKCS11ConnectionInfo{
			ModuleID:   c.ModuleID,
			SlotID:     c.SlotID,
			TokenLabel: c.TokenLabel,
		}
	}
	return result
}

// convertModule converts a manager.ModuleInfo to PKCS11ModuleInfo.
func convertModule(m *manager.ModuleInfo) *PKCS11ModuleInfo {
	return &PKCS11ModuleInfo{
		ID:          m.ID,
		DisplayName: m.DisplayName,
		LibraryPath: m.LibraryPath,
		State:       m.State.String(),
		Slots:       convertSlots(m.Slots),
		ErrorMsg:    m.ErrorMsg,
	}
}

// convertSlots converts a slice of manager.SlotInfo to PKCS11SlotInfo.
func convertSlots(slots []manager.SlotInfo) []PKCS11SlotInfo {
	result := make([]PKCS11SlotInfo, len(slots))
	for i, slot := range slots {
		result[i] = PKCS11SlotInfo{
			SlotID:          slot.SlotID,
			Label:           slot.Label,
			Serial:          slot.Serial,
			Manufacturer:    slot.Manufacturer,
			Model:           slot.Model,
			TokenPresent:    slot.TokenPresent,
			Initialized:     slot.Initialized,
			HardwareVersion: slot.HardwareVersion,
			FirmwareVersion: slot.FirmwareVersion,
		}
	}
	return result
}

// TestConnection tests connectivity to a PKCS#11 module by attempting to
// register, connect to the specified slot, and then clean up. This allows
// validating configuration before permanently adding the backend.
func (s *PKCS11Service) TestConnection(libraryPath string, slotID uint, userPIN string) error {
	if s.manager == nil {
		return ErrPKCS11ServiceNotInitialized
	}
	if libraryPath == "" {
		return ErrPKCS11ModuleRequired
	}
	if userPIN == "" {
		return ErrPKCS11UserPINRequired
	}

	s.log.Info("testing PKCS#11 connection",
		"library", libraryPath,
		"slot_id", slotID)

	// Auto-configure SoftHSM2 if needed
	if isSoftHSM2Module(libraryPath) {
		if err := s.ensureSoftHSM2Config(); err != nil {
			s.log.Error("failed to configure SoftHSM2", "error", err)
			return fmt.Errorf("SoftHSM2 configuration failed: %w", err)
		}
	}

	// Register the module temporarily
	moduleID, err := s.manager.RegisterModule(libraryPath, "test-connection")
	if err != nil {
		s.log.Error("test connection: failed to register module", "error", err)
		return fmt.Errorf("failed to register module: %w", err)
	}

	// Get module info to show available slots
	mod, modErr := s.manager.GetModule(moduleID)
	if modErr == nil {
		s.log.Debug("test connection: module info",
			"slots", len(mod.Slots))
		for _, slot := range mod.Slots {
			s.log.Debug("test connection: slot",
				"slot_id", slot.SlotID,
				"label", slot.Label,
				"token_present", slot.TokenPresent,
				"initialized", slot.Initialized)
		}
	}

	// Try to login to the specified slot (lightweight test, no full backend)
	loginErr := s.manager.TestLogin(moduleID, slotID, userPIN)
	if loginErr != nil {
		s.log.Error("test connection: login failed",
			"slot_id", slotID,
			"error", loginErr)
	} else {
		s.log.Info("test connection: success",
			"slot_id", slotID)
	}

	if loginErr != nil {
		// Cleanup: unregister the module on failure so the next attempt
		// starts fresh (e.g., after the user corrects the PIN).
		_ = s.manager.UnregisterModule(moduleID)
		return fmt.Errorf("connection test failed: %w", loginErr)
	}

	// Retain the registration so a subsequent RegisterModule call for the
	// same library can reuse it without paying the C_Initialize cost again.
	if s.testedModules == nil {
		s.testedModules = make(map[string]string)
	}
	s.testedModulesMu.Lock()
	s.testedModules[libraryPath] = moduleID
	s.testedModulesMu.Unlock()

	return nil
}

// ProbeSlots temporarily registers a PKCS#11 module to enumerate its available
// slots, then immediately unregisters it. This allows the UI to show available
// slots before the user commits to adding the backend.
func (s *PKCS11Service) ProbeSlots(libraryPath string) ([]PKCS11SlotInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}
	if libraryPath == "" {
		return nil, ErrPKCS11ModuleRequired
	}

	s.log.Info("probing PKCS#11 module slots",
		"library", libraryPath)

	// Auto-configure SoftHSM2 if needed
	if isSoftHSM2Module(libraryPath) {
		if err := s.ensureSoftHSM2Config(); err != nil {
			s.log.Error("failed to configure SoftHSM2", "error", err)
			return nil, fmt.Errorf("SoftHSM2 configuration failed: %w", err)
		}
	}

	// Register the module temporarily
	moduleID, err := s.manager.RegisterModule(libraryPath, "probe-slots")
	if err != nil {
		s.log.Error("probe slots: failed to register module", "error", err)
		return nil, fmt.Errorf("failed to probe module: %w", err)
	}

	// Get module info to retrieve slots
	mod, err := s.manager.GetModule(moduleID)
	if err != nil {
		_ = s.manager.UnregisterModule(moduleID)
		return nil, fmt.Errorf("failed to get module info: %w", err)
	}

	// Convert slots
	slots := convertSlots(mod.Slots)

	s.log.Info("probe slots: found slots",
		"count", len(slots))
	for _, slot := range slots {
		s.log.Debug("probe slots: slot info",
			"slot_id", slot.SlotID,
			"label", slot.Label,
			"initialized", slot.Initialized)
	}

	// Unregister the module
	_ = s.manager.UnregisterModule(moduleID)

	return slots, nil
}

// SlotOccupancyInfo describes a single PIV slot's state for the frontend.
type SlotOccupancyInfo struct {
	Slot         string `json:"slot"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Occupied     bool   `json:"occupied"`
	KeyAlgorithm string `json:"key_algorithm,omitempty"`
	HasCert      bool   `json:"has_cert"`
}

// slotModelProvider is the interface for backends that expose PIV slot models.
// The manager.Backend interface does not include SlotModel(), but the concrete
// pkcs11.Backend type does. This local interface allows a clean type assertion
// without importing the concrete backend package.
type slotModelProvider interface {
	SlotModel() pivcert.SlotModel
}

// GetSlotOccupancy returns PIV slot occupancy for the connected PKCS#11 token.
// Returns nil with no error if the token does not use predefined slots (generic PKCS#11).
func (s *PKCS11Service) GetSlotOccupancy(moduleID string, slotID uint) ([]SlotOccupancyInfo, error) {
	if s.manager == nil {
		return nil, ErrPKCS11ServiceNotInitialized
	}

	conn, err := s.manager.GetConnection(moduleID, slotID)
	if err != nil {
		return nil, err
	}

	if conn.Backend == nil {
		return nil, nil
	}

	smp, ok := conn.Backend.(slotModelProvider)
	if !ok {
		return nil, nil
	}

	sm := smp.SlotModel()
	if sm == nil {
		return nil, nil
	}

	// Refresh to get latest state from token.
	if refreshErr := sm.Refresh(); refreshErr != nil {
		s.log.Warn("slot model refresh failed", "error", refreshErr)
	}

	allSlots := sm.AllSlots()
	result := make([]SlotOccupancyInfo, 0, len(allSlots))
	for _, slot := range allSlots {
		info, infoErr := sm.SlotOccupancy(slot)
		if infoErr != nil {
			continue
		}
		result = append(result, SlotOccupancyInfo{
			Slot:         string(info.Slot),
			Name:         info.Name,
			Description:  info.Description,
			Occupied:     info.Occupied,
			KeyAlgorithm: info.KeyAlgorithm,
			HasCert:      info.HasCert,
		})
	}
	return result, nil
}

// YubiKeyDetectionResult describes the outcome of a YubiKey library probe.
type YubiKeyDetectionResult struct {
	Found       bool   `json:"found"`
	LibraryPath string `json:"library_path,omitempty"`
	Error       string `json:"error,omitempty"`
}

// yubiKeyLibraryPaths lists common installation paths for the Yubico
// PKCS#11 module across Linux architectures and package managers.
var yubiKeyLibraryPaths = []string{
	"/usr/lib/x86_64-linux-gnu/libykcs11.so",
	"/usr/lib/aarch64-linux-gnu/libykcs11.so",
	"/usr/lib/libykcs11.so",
	"/usr/local/lib/libykcs11.so",
	"/opt/yubico/lib/libykcs11.so",
}

// DetectYubiKey probes the filesystem for the Yubico PKCS#11 module
// (libykcs11.so) and returns the first path found.
func (s *PKCS11Service) DetectYubiKey() YubiKeyDetectionResult {
	for _, p := range yubiKeyLibraryPaths {
		if _, err := os.Stat(p); err == nil {
			s.log.Info("YubiKey PKCS#11 module detected", "path", p)
			return YubiKeyDetectionResult{
				Found:       true,
				LibraryPath: p,
			}
		}
	}
	s.log.Debug("YubiKey PKCS#11 module not found on any known path")
	return YubiKeyDetectionResult{
		Found: false,
		Error: "libykcs11.so not found in any known location",
	}
}

// HasSlotModel reports whether the connected token uses predefined PIV slots.
func (s *PKCS11Service) HasSlotModel(moduleID string, slotID uint) bool {
	if s.manager == nil {
		return false
	}
	conn, err := s.manager.GetConnection(moduleID, slotID)
	if err != nil || conn.Backend == nil {
		return false
	}
	smp, ok := conn.Backend.(slotModelProvider)
	return ok && smp.SlotModel() != nil
}
