// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-xkms.
//
// go-xkms is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

package agent

import "time"

// EnrollmentMethod defines the type of enrollment used when an agent
// registers with the master.
type EnrollmentMethod string

const (
	// EnrollOneTimeCode uses a short-lived code generated by the master.
	// The agent presents the code along with a CSR to obtain a certificate.
	EnrollOneTimeCode EnrollmentMethod = "one_time_code"

	// EnrollAdminApproval requires an administrator to manually approve
	// the enrollment request after the agent submits a CSR.
	EnrollAdminApproval EnrollmentMethod = "admin_approval"

	// EnrollEnterpriseCA trusts an external enterprise CA. Any agent
	// presenting a certificate signed by the trusted CA is accepted.
	EnrollEnterpriseCA EnrollmentMethod = "enterprise_ca"

	// EnrollNoiseDirect uses the Noise protocol for direct pairing
	// between the master and agent without a pre-existing PKI.
	EnrollNoiseDirect EnrollmentMethod = "noise_direct"
)

// validEnrollmentMethods is used for O(1) validation of enrollment methods.
var validEnrollmentMethods = map[EnrollmentMethod]struct{}{
	EnrollOneTimeCode:   {},
	EnrollAdminApproval: {},
	EnrollEnterpriseCA:  {},
	EnrollNoiseDirect:   {},
}

// IsValidEnrollmentMethod reports whether m is a recognized enrollment method.
func IsValidEnrollmentMethod(m EnrollmentMethod) bool {
	_, ok := validEnrollmentMethods[m]
	return ok
}

// Config holds the agent server configuration. The security officer sets
// enrollment policy through this configuration.
type Config struct {
	// ListenAddress is the address the agent server binds to (e.g., ":9443").
	ListenAddress string `yaml:"listen_address" json:"listen_address" mapstructure:"listen_address"`

	// TLSCertFile is the path to the server TLS certificate.
	TLSCertFile string `yaml:"tls_cert_file" json:"tls_cert_file" mapstructure:"tls_cert_file"`

	// TLSKeyFile is the path to the server TLS private key.
	TLSKeyFile string `yaml:"tls_key_file" json:"tls_key_file" mapstructure:"tls_key_file"`

	// TLSCAFile is the path to the CA certificate for client verification.
	TLSCAFile string `yaml:"tls_ca_file" json:"tls_ca_file" mapstructure:"tls_ca_file"`

	// EnrollmentMethods lists the enrollment methods permitted by policy.
	// At least one method must be configured for agents to enroll.
	EnrollmentMethods []EnrollmentMethod `yaml:"enrollment_methods" json:"enrollment_methods" mapstructure:"enrollment_methods"`

	// RequireAttestation requires agents to present platform attestation
	// evidence during enrollment.
	RequireAttestation bool `yaml:"require_attestation" json:"require_attestation" mapstructure:"require_attestation"`

	// CertValidityDays is the validity period for issued agent certificates.
	CertValidityDays int `yaml:"cert_validity_days" json:"cert_validity_days" mapstructure:"cert_validity_days"`

	// MaxAgents is the maximum number of agents that can be enrolled.
	// Zero means unlimited.
	MaxAgents int `yaml:"max_agents" json:"max_agents" mapstructure:"max_agents"`

	// OneTimeCodeLength is the length of generated one-time enrollment codes.
	OneTimeCodeLength int `yaml:"one_time_code_length" json:"one_time_code_length" mapstructure:"one_time_code_length"`

	// OneTimeCodeValidity is the default validity duration for one-time codes.
	OneTimeCodeValidity time.Duration `yaml:"one_time_code_validity" json:"one_time_code_validity" mapstructure:"one_time_code_validity"`
}

// DefaultConfig returns a Config with sensible defaults. The listen address
// defaults to :9443, certificates are valid for 365 days, and one-time-code
// enrollment is enabled.
func DefaultConfig() *Config {
	return &Config{
		ListenAddress: ":9443",
		EnrollmentMethods: []EnrollmentMethod{
			EnrollOneTimeCode,
		},
		CertValidityDays:    365,
		MaxAgents:           0,
		OneTimeCodeLength:   8,
		OneTimeCodeValidity: 15 * time.Minute,
	}
}

// Validate checks the configuration for semantic correctness. It returns
// a typed error if any field contains an invalid or missing value.
func (c *Config) Validate() error {
	if c.ListenAddress == "" {
		return &AgentError{Operation: "validate_config", Err: ErrInvalidAddress}
	}
	for _, m := range c.EnrollmentMethods {
		if !IsValidEnrollmentMethod(m) {
			return &AgentError{
				Operation: "validate_config",
				Err:       ErrPolicyViolation,
			}
		}
	}
	if c.CertValidityDays <= 0 {
		c.CertValidityDays = 365
	}
	if c.OneTimeCodeLength <= 0 {
		c.OneTimeCodeLength = 8
	}
	if c.OneTimeCodeValidity <= 0 {
		c.OneTimeCodeValidity = 15 * time.Minute
	}
	return nil
}

// ClientConfig holds the remote agent client settings for connecting
// to a master xKey instance.
type ClientConfig struct {
	// MasterAddress is the address of the master agent server.
	MasterAddress string `yaml:"master_address" json:"master_address" mapstructure:"master_address"`

	// TLSCertFile is the path to the client TLS certificate (issued during enrollment).
	TLSCertFile string `yaml:"tls_cert_file" json:"tls_cert_file" mapstructure:"tls_cert_file"`

	// TLSKeyFile is the path to the client TLS private key.
	TLSKeyFile string `yaml:"tls_key_file" json:"tls_key_file" mapstructure:"tls_key_file"`

	// TLSCAFile is the path to the CA certificate for server verification.
	TLSCAFile string `yaml:"tls_ca_file" json:"tls_ca_file" mapstructure:"tls_ca_file"`

	// LocalAddress is the local address for reverse-proxy services
	// (e.g., "localhost:19443").
	LocalAddress string `yaml:"local_address" json:"local_address" mapstructure:"local_address"`

	// ReconnectBackoffMax is the maximum backoff duration between reconnect
	// attempts. Zero means no reconnection.
	ReconnectBackoffMax time.Duration `yaml:"reconnect_backoff_max" json:"reconnect_backoff_max" mapstructure:"reconnect_backoff_max"`
}

// DefaultClientConfig returns a ClientConfig with sensible defaults.
func DefaultClientConfig() *ClientConfig {
	return &ClientConfig{
		LocalAddress:        "localhost:19443",
		ReconnectBackoffMax: 2 * time.Minute,
	}
}

// Validate checks the client configuration for semantic correctness.
func (c *ClientConfig) Validate() error {
	if c.MasterAddress == "" {
		return &AgentError{Operation: "validate_client_config", Err: ErrInvalidAddress}
	}
	return nil
}
