// Copyright (c) 2025 Jeremy Hahn
// Copyright (c) 2025 Automate The Things, LLC
//
// This file is part of go-xkms.
//
// go-xkms is dual-licensed:
//
// 1. GNU Affero General Public License v3.0 (AGPL-3.0)
//    See LICENSE file or visit https://www.gnu.org/licenses/agpl-3.0.html
//
// 2. Commercial License
//    Contact licensing@automatethethings.com for commercial licensing options.

package agent

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"log/slog"
	"sync"
	"time"
)

// CAService is the interface for certificate authority operations used
// by the enrollment service. Implementations must be safe for concurrent use.
type CAService interface {
	// SignCSR signs a PEM-encoded PKCS#10 certificate signing request and
	// returns the signed certificate as PEM.
	SignCSR(csrPEM []byte) (certPEM []byte, err error)

	// GetCACertificate returns the CA certificate as PEM-encoded bytes.
	GetCACertificate() ([]byte, error)

	// RevokeCertificate revokes a certificate identified by its serial number.
	RevokeCertificate(serialNumber string) error
}

// EnrollmentStore persists enrolled agent state. Implementations must
// be safe for concurrent use.
type EnrollmentStore interface {
	// SaveAgent persists an agent record, creating or updating as needed.
	SaveAgent(agent *AgentInfo) error

	// GetAgent retrieves an agent by its ID. Returns ErrAgentNotFound
	// if the agent does not exist.
	GetAgent(id string) (*AgentInfo, error)

	// ListAgents returns all enrolled agents.
	ListAgents() ([]*AgentInfo, error)

	// DeleteAgent removes an agent by its ID. Returns ErrAgentNotFound
	// if the agent does not exist.
	DeleteAgent(id string) error
}

// AgentInfo describes an enrolled remote agent.
type AgentInfo struct {
	// ID is a unique identifier for the agent derived from the certificate
	// fingerprint.
	ID string `json:"id"`

	// Name is a human-readable name assigned during enrollment.
	Name string `json:"name"`

	// Address is the last known address of the agent.
	Address string `json:"address"`

	// CertificateFingerprint is the SHA-256 fingerprint of the agent's
	// certificate in hex-encoded form.
	CertificateFingerprint string `json:"certificate_fingerprint"`

	// EnrolledAt is the time the agent was enrolled.
	EnrolledAt time.Time `json:"enrolled_at"`

	// LastSeen is the time the agent was last seen connected.
	LastSeen time.Time `json:"last_seen"`

	// Status describes the current enrollment status (e.g., "active",
	// "revoked").
	Status string `json:"status"`
}

// OneTimeCode is a short-lived enrollment code generated by the master.
type OneTimeCode struct {
	// Code is the random code string presented by the agent.
	Code string `json:"code"`

	// ExpiresAt is the time after which the code is no longer valid.
	ExpiresAt time.Time `json:"expires_at"`

	// Used marks whether this code has been consumed.
	Used bool `json:"used"`
}

// PendingEnrollment represents an enrollment request awaiting admin approval.
type PendingEnrollment struct {
	// ID is a unique identifier for this enrollment request.
	ID string `json:"id"`

	// CSR is the PEM-encoded certificate signing request.
	CSR []byte `json:"csr"`

	// Fingerprint is the SHA-256 fingerprint of the CSR public key.
	Fingerprint string `json:"fingerprint"`

	// RequestedAt is the time the request was submitted.
	RequestedAt time.Time `json:"requested_at"`

	// Status is the current state: "pending", "approved", or "rejected".
	Status string `json:"status"`

	// Reason is set when the request is rejected to explain why.
	Reason string `json:"reason,omitempty"`
}

// EnrollmentService manages agent enrollment and certificate issuance.
// It supports all four enrollment methods and enforces the enrollment
// policy from the Config. Thread-safe.
type EnrollmentService struct {
	config  *Config
	ca      CAService
	store   EnrollmentStore
	logger  *slog.Logger
	codes   map[string]*OneTimeCode
	pending map[string]*PendingEnrollment
	mu      sync.RWMutex
}

// NewEnrollmentService creates a new EnrollmentService. Returns an error
// if any required parameter is nil.
func NewEnrollmentService(cfg *Config, ca CAService, store EnrollmentStore, logger *slog.Logger) (*EnrollmentService, error) {
	if cfg == nil {
		return nil, ErrNilConfig
	}
	if ca == nil {
		return nil, ErrNilCAService
	}
	if store == nil {
		return nil, ErrNilEnrollmentStore
	}
	if logger == nil {
		return nil, ErrNilLogger
	}
	return &EnrollmentService{
		config:  cfg,
		ca:      ca,
		store:   store,
		logger:  logger,
		codes:   make(map[string]*OneTimeCode),
		pending: make(map[string]*PendingEnrollment),
	}, nil
}

// GenerateOneTimeCode creates a short-lived enrollment code. The validity
// duration determines how long the code is usable. If validity is zero,
// the configured default is used.
func (s *EnrollmentService) GenerateOneTimeCode(validity time.Duration) (*OneTimeCode, error) {
	if !s.IsMethodAllowed(EnrollOneTimeCode) {
		return nil, ErrEnrollmentMethodNotAllowed
	}

	if validity <= 0 {
		validity = s.config.OneTimeCodeValidity
	}

	code, err := generateSecureCode(s.config.OneTimeCodeLength)
	if err != nil {
		return nil, &AgentError{Operation: "generate_code", Err: err}
	}

	otc := &OneTimeCode{
		Code:      code,
		ExpiresAt: time.Now().Add(validity),
		Used:      false,
	}

	s.mu.Lock()
	s.codes[code] = otc
	s.mu.Unlock()

	s.logger.Info("generated one-time enrollment code",
		"expires_at", otc.ExpiresAt.Format(time.RFC3339))

	return otc, nil
}

// EnrollWithCode validates a one-time code and issues a certificate for
// the provided CSR. Returns the signed certificate PEM and the CA
// certificate PEM.
func (s *EnrollmentService) EnrollWithCode(code string, csrPEM []byte) (certPEM, caPEM []byte, err error) {
	if !s.IsMethodAllowed(EnrollOneTimeCode) {
		return nil, nil, ErrEnrollmentMethodNotAllowed
	}
	if len(csrPEM) == 0 {
		return nil, nil, ErrInvalidCSR
	}

	s.mu.Lock()
	otc, ok := s.codes[code]
	if !ok {
		s.mu.Unlock()
		return nil, nil, ErrEnrollmentCodeInvalid
	}
	if otc.Used {
		s.mu.Unlock()
		return nil, nil, ErrEnrollmentCodeInvalid
	}
	if time.Now().After(otc.ExpiresAt) {
		delete(s.codes, code)
		s.mu.Unlock()
		return nil, nil, ErrEnrollmentCodeExpired
	}
	otc.Used = true
	delete(s.codes, code)
	s.mu.Unlock()

	// Check max agents limit.
	if err := s.checkMaxAgents(); err != nil {
		return nil, nil, err
	}

	// Validate the CSR.
	fingerprint, err := csrFingerprint(csrPEM)
	if err != nil {
		return nil, nil, &AgentError{Operation: "enroll_with_code", Err: err}
	}

	// Sign the CSR.
	certPEM, err = s.ca.SignCSR(csrPEM)
	if err != nil {
		return nil, nil, &AgentError{Operation: "enroll_with_code", Err: err}
	}

	// Get CA certificate.
	caPEM, err = s.ca.GetCACertificate()
	if err != nil {
		return nil, nil, &AgentError{Operation: "enroll_with_code", Err: err}
	}

	// Record the enrollment.
	agentInfo := &AgentInfo{
		ID:                     fingerprint,
		Name:                   "agent-" + fingerprint[:8],
		CertificateFingerprint: fingerprint,
		EnrolledAt:             time.Now(),
		LastSeen:               time.Now(),
		Status:                 "active",
	}
	if storeErr := s.store.SaveAgent(agentInfo); storeErr != nil {
		s.logger.Warn("failed to persist agent enrollment",
			"fingerprint", fingerprint,
			"error", storeErr)
	}

	s.logger.Info("agent enrolled via one-time code",
		"agent_id", agentInfo.ID)

	return certPEM, caPEM, nil
}

// SubmitEnrollmentRequest submits a CSR for admin approval. Returns the
// request ID that the administrator uses to approve or reject the request.
func (s *EnrollmentService) SubmitEnrollmentRequest(csrPEM []byte) (string, error) {
	if !s.IsMethodAllowed(EnrollAdminApproval) {
		return "", ErrEnrollmentMethodNotAllowed
	}
	if len(csrPEM) == 0 {
		return "", ErrInvalidCSR
	}

	// Check max agents limit.
	if err := s.checkMaxAgents(); err != nil {
		return "", err
	}

	fingerprint, err := csrFingerprint(csrPEM)
	if err != nil {
		return "", &AgentError{Operation: "submit_enrollment", Err: err}
	}

	requestID, err := generateSecureCode(16)
	if err != nil {
		return "", &AgentError{Operation: "submit_enrollment", Err: err}
	}

	pending := &PendingEnrollment{
		ID:          requestID,
		CSR:         csrPEM,
		Fingerprint: fingerprint,
		RequestedAt: time.Now(),
		Status:      "pending",
	}

	s.mu.Lock()
	s.pending[requestID] = pending
	s.mu.Unlock()

	s.logger.Info("enrollment request submitted",
		"request_id", requestID,
		"fingerprint", fingerprint)

	return requestID, nil
}

// ApproveEnrollment approves a pending enrollment request, signs the CSR,
// and returns the signed certificate PEM and CA certificate PEM.
func (s *EnrollmentService) ApproveEnrollment(requestID string) (certPEM, caPEM []byte, err error) {
	if requestID == "" {
		return nil, nil, ErrInvalidRequestID
	}

	s.mu.Lock()
	pending, ok := s.pending[requestID]
	if !ok {
		s.mu.Unlock()
		return nil, nil, ErrRequestNotFound
	}
	if pending.Status != "pending" {
		s.mu.Unlock()
		if pending.Status == "rejected" {
			return nil, nil, ErrEnrollmentRejected
		}
		return nil, nil, ErrEnrollmentFailed
	}
	pending.Status = "approved"
	s.mu.Unlock()

	// Sign the CSR.
	certPEM, err = s.ca.SignCSR(pending.CSR)
	if err != nil {
		return nil, nil, &AgentError{Operation: "approve_enrollment", Err: err}
	}

	// Get CA certificate.
	caPEM, err = s.ca.GetCACertificate()
	if err != nil {
		return nil, nil, &AgentError{Operation: "approve_enrollment", Err: err}
	}

	// Record the enrollment.
	agentInfo := &AgentInfo{
		ID:                     pending.Fingerprint,
		Name:                   "agent-" + pending.Fingerprint[:8],
		CertificateFingerprint: pending.Fingerprint,
		EnrolledAt:             time.Now(),
		LastSeen:               time.Now(),
		Status:                 "active",
	}
	if storeErr := s.store.SaveAgent(agentInfo); storeErr != nil {
		s.logger.Warn("failed to persist agent enrollment",
			"fingerprint", pending.Fingerprint,
			"error", storeErr)
	}

	// Remove from pending.
	s.mu.Lock()
	delete(s.pending, requestID)
	s.mu.Unlock()

	s.logger.Info("enrollment approved",
		"request_id", requestID,
		"agent_id", agentInfo.ID)

	return certPEM, caPEM, nil
}

// RejectEnrollment rejects a pending enrollment request with the given reason.
func (s *EnrollmentService) RejectEnrollment(requestID string, reason string) error {
	if requestID == "" {
		return ErrInvalidRequestID
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	pending, ok := s.pending[requestID]
	if !ok {
		return ErrRequestNotFound
	}
	if pending.Status != "pending" {
		return ErrEnrollmentFailed
	}

	pending.Status = "rejected"
	pending.Reason = reason

	s.logger.Info("enrollment rejected",
		"request_id", requestID,
		"reason", reason)

	return nil
}

// ListPending returns all pending enrollment requests.
func (s *EnrollmentService) ListPending() ([]*PendingEnrollment, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	result := make([]*PendingEnrollment, 0, len(s.pending))
	for _, p := range s.pending {
		if p.Status == "pending" {
			result = append(result, p)
		}
	}
	return result, nil
}

// IsMethodAllowed checks if an enrollment method is allowed by the
// current policy configuration.
func (s *EnrollmentService) IsMethodAllowed(method EnrollmentMethod) bool {
	for _, m := range s.config.EnrollmentMethods {
		if m == method {
			return true
		}
	}
	return false
}

// CleanExpiredCodes removes all expired one-time codes from memory.
func (s *EnrollmentService) CleanExpiredCodes() int {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := time.Now()
	removed := 0
	for code, otc := range s.codes {
		if now.After(otc.ExpiresAt) {
			delete(s.codes, code)
			removed++
		}
	}
	return removed
}

// checkMaxAgents checks whether the maximum enrolled agent limit has been
// reached. Returns nil if no limit is set or the limit has not been reached.
func (s *EnrollmentService) checkMaxAgents() error {
	if s.config.MaxAgents <= 0 {
		return nil
	}
	agents, err := s.store.ListAgents()
	if err != nil {
		return &AgentError{Operation: "check_max_agents", Err: err}
	}
	if len(agents) >= s.config.MaxAgents {
		return ErrMaxAgentsReached
	}
	return nil
}

// generateSecureCode generates a cryptographically random hex string of
// the given length (in characters).
func generateSecureCode(length int) (string, error) {
	// Each byte produces 2 hex characters; round up.
	numBytes := (length + 1) / 2
	buf := make([]byte, numBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf)[:length], nil
}

// csrFingerprint parses a PEM-encoded CSR and returns the SHA-256
// fingerprint of its public key in hex-encoded form.
func csrFingerprint(csrPEM []byte) (string, error) {
	block, _ := pem.Decode(csrPEM)
	if block == nil {
		return "", ErrInvalidCSR
	}
	csr, err := x509.ParseCertificateRequest(block.Bytes)
	if err != nil {
		return "", ErrInvalidCSR
	}
	if err := csr.CheckSignature(); err != nil {
		return "", ErrInvalidCSR
	}
	pubKeyBytes, err := x509.MarshalPKIXPublicKey(csr.PublicKey)
	if err != nil {
		return "", ErrInvalidCSR
	}
	hash := sha256.Sum256(pubKeyBytes)
	return hex.EncodeToString(hash[:]), nil
}
